# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
  branches:
    include:
      - master
      - sdtttttt
      - CICD
      - depend*
  paths:
    exclude:
      - README.md
      - appveyor.yml

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.6.3'

- script: sudo apt-get -yqq install libsqlite3-dev libpq-dev
  displayName: install sqlite3

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec rake
  displayName: 'bundle exec rake'
